import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Puertajada - Influencer y Creador de Contenido",
  description: "Descubre el contenido más divertido de Puertajada, el famoso influencer conocido por sus videos virales y su humor único. Síguelo en todas sus redes sociales.",
  keywords: ["Puertajada", "influencer", "contenido viral", "humor", "redes sociales", "TikTok", "YouTube", "Instagram"],
  authors: [{ name: "Puertajada" }],
  creator: "Puertajada",
  publisher: "Puertajada",
  robots: "index, follow",
  openGraph: {
    type: "website",
    locale: "es_ES",
    url: "https://puertajada.com",
    title: "Puertajada - Influencer y Creador de Contenido",
    description: "Descubre el contenido más divertido de Puertajada, el famoso influencer conocido por sus videos virales y su humor único.",
    siteName: "Puertajada",
    images: [
      {
        url: "/icon.jpg",
        width: 1200,
        height: 630,
        alt: "Puertajada - Influencer",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Puertajada - Influencer y Creador de Contenido",
    description: "Descubre el contenido más divertido de Puertajada, el famoso influencer conocido por sus videos virales.",
    creator: "@puertajada",
    images: ["/icon.jpg"],
  },
  icons: {
    icon: [
      { url: "/icon.jpg", sizes: "32x32", type: "image/jpeg" },
      { url: "/icon.jpg", sizes: "16x16", type: "image/jpeg" },
    ],
    apple: [
      { url: "/icon.jpg", sizes: "180x180", type: "image/jpeg" },
    ],
    shortcut: "/icon.jpg",
  },
  manifest: "/manifest.json",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 415a83f11a3f3402294508ecf86d09b5847f81fb
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="es">
      <head>
        <meta name="theme-color" content="#000000" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <link rel="canonical" href="https://puertajada.com" />
      </head>
=======
    <html lang="en">
>>>>>>> 415a83f11a3f3402294508ecf86d09b5847f81fb
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
